# Generated by Django 4.0.6 on 2022-10-04 15:57

import discordoauth2.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_class',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('discord_tag', models.CharField(max_length=30)),
                ('avatar', models.CharField(max_length=200)),
                ('public_flags', models.IntegerField()),
                ('flags', models.BigIntegerField()),
                ('locale', models.CharField(max_length=100)),
                ('mfa_enabled', models.BooleanField()),
                ('last_login', models.DateTimeField(null=True)),
                ('family_name', models.CharField(max_length=15, null=True)),
                ('guild_code', models.CharField(max_length=100, null=True)),
            ],
            managers=[
                ('objects', discordoauth2.managers.DiscordUserManager()),
            ],
        ),
    ]
